---
# Set up package repositories

- name: reconfigure locales
  shell: dpkg-reconfigure locales

- name: update-locale utf8
  shell: update-locale LANG=en_US.UTF-8

- name: Ensure APT sources list includes multiverse
  copy: src={{ ansible_distribution }}/{{ ansible_distribution_release }}/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0444
  when: ansible_distribution == 'Ubuntu'
  
- name: Patch cloud-init APT sources template
  copy: src={{ ansible_distribution }}/{{ ansible_distribution_release }}/sources.list.tmpl dest=/etc/cloud/templates/sources.list.tmpl owner=root group=root mode=0444
  when: ansible_distribution == 'Ubuntu' and cloud_provider == 'AWS'


  
