---
- name: Install packages
  apt: name={{ item }}
  with_items:
    - redis-server

- name: Configure redis
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify: restart redis 

- name: Enable and start redis-server
  service: name=redis-server enabled=yes state=started
  when: docker == false

- name: Configure redis-rb
  template: src=redis.rb.j2 dest={{ app_config_path }}/initializers/redis.rb owner={{ user_name }} backup=yes
  when: redis_orm is defined and redis_orm == 'redis-rb'
 
- name: Create upstart config
  template: src=upstart.conf.j2 dest=/etc/init/redis.conf
  when: docker == false
  notify: restart redis

- name: Create redis runit directory
  file:
    path=/etc/service/{{ redis_service_name }}
    state=directory
    owner=root
    group=root
    mode=0755
  when: docker == true
  tags: service 

- name: Add redis runit script
  template:
    src=runit-template.j2
    dest=/etc/service/{{ redis_service_name }}/run
    owner=root
    group=root
    mode=0755
  when: docker == true
  tags: service
