---
galaxy_info:
  author: Matthew Long
  description: Hybris Commerce Platform 
  company: isobar
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  categories:
  - clustering
  - database
dependencies: []
