---

- name: Create Tomcat runit directory
  file:
    path=/etc/service/{{ tomcat_service_name }}
    state=directory
    owner=root
    group=root
    mode=0755
  tags: tomcat

- name: Install runit Tomcat Service
  tags: tomcat
  template:
    src={{ tomcat_server_runit_template }}
    dest=/etc/service/{{ tomcat_service_name }}/run
    owner=0
    group=0
    mode=0755
