# file: mysql/tasks/install.yml

- name: MySQL | Load the os specific variables
  include_vars: "{{ansible_os_family | lower}}.yml"

- name: MySQL | Make sure the MySql packages are installed
  apt:
    pkg: "{{item}}"
    update_cache: yes
  with_items: mysql_packages

- name: MySQL | Ensure MySQL is running
  service: name=mysql enabled=yes state=started
  when: docker == false

- name: MySQL | Start MySQL
  shell: /etc/init.d/mysql start
  when: docker == false

- name: Create mysql runit directory
  file:
    path=/etc/service/{{ mysql_service_name }}
    state=directory
    owner=root
    group=root
    mode=0755
  when: docker == true
  tags: service

- name: Add mysql runit script
  template:
    src=runit-template.j2
    dest=/etc/service/{{ mysql_service_name }}/run
    owner=root
    group=root
    mode=0755
  when: docker == true
  tags: service

- name: start mysql runit service
  shell: sv start mysql
  when: docker == true
