---

- include: ubuntu.yml

- include: install.yml
  when: solr_action == 'install'
  tags: [ 'solr', 'solr_install' ]

- include: install_conf.yml
  when: solr_action_core == 'install_core'
  tags: [ 'solr', 'solr_install_core' ]

- include: install_core.yml
  when: solr_action_core == 'install_core'
  tags: [ 'solr', 'solr_install_core' ]

