---
# Tomcat version number
tomcat_version: 7.0.57

# Mirror where to dowload Tomcat redistributable package from
tomcat_mirror: http://archive.apache.org/dist/tomcat

tomcat_download_url: "{{ tomcat_mirror }}/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/{{ tomcat_redis_filename }}"

# tomcat service user
#   user name
tomcat_user_name: tomcat
#   group name
tomcat_user_group: tomcat
#   user's home directory
tomcat_user_home: "/srv/{{ tomcat_user_name }}"

# tomcat installation directories
#   base directory for tomcat installations
tomcat_install_base: /opt/tomcat


# Enable Ubuntu sysvinit or upstart
upstart: ""
sysvinit: ""
runit: "yes"

# tomcat init script options
daemon: "{{ tomcat_env_catalina_home }}/bin/catalina.sh"
daemon_opts: "start"
pidfile: "{{ tomcat_env_catalina_base }}/pid/tomcat.pid"

# tomcat instance
#   instance directory, denoted by environment variable CATALINA_BASE
tomcat_env_catalina_base: "{{ tomcat_user_home }}/catalina"
#   service name
tomcat_service_name: "{{ tomcat_user_name }}"
#   template for configuration files
tomcat_server_xml_template: server.xml.j2
# template for user configuration files
tomcat_users_xml_template: tomcat-users.xml.j2
#   template for upstart
tomcat_server_upstart_template: service_upstart.j2
#   template for sysvinit
tomcat_server_sysvinit_template: service_sysvinit.j2
#  template for ubuntu init
tomcat_server_init_template: service_init.j2
#  template for ubuntu runit
tomcat_server_runit_template: service_runit.j2
#   template for systemd
tomcat_server_systemd_template: service_systemd.j2
# Tomcat Role Names
#tomcat_role_set: 
#tomcat_role_name: 
# Tomcat Usernames 
tomcat_user_set: yes
tomcat_username: 
        - deploy
tomcat_password: 
        - x3LfM58oq1iC
tomcat_roles: 
        - manager-script
#  Java Home
java_home: /opt/jdk/jdk1.7.0_60
# Catalina Opts
tomcat_env_catalina_opts: "-Xms2048m -Xmx4096m -XX:MaxPermSize=256m"
